apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: backend
        image: hustshawn/k8s-demo:main
        imagePullPolicy: Always
        # command:
        #   - flask
        #   - run
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
