apiVersion: v1
kind: Service
metadata:
  name: backend-app-svc
  namespace: default
spec:
  ports:
  - port: 5000
    targetPort: http
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP
